name: Deploy Documentation

on:
  push:
    branches:
      - 'dev_docs'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install foxes
      run: |
        pip install -e .[doc]
        pip uninstall -y nbsphinx
        pip install git+https://github.com/SchmJo/nbsphinx.git@master
    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: docs/build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
